"""add chonges

Revision ID: 5e7de21c0919
Revises: 0001_initial_tables
Create Date: 2026-08-20 08:11:05.701109
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '5e7de21c0919'
down_revision: Union[str, None] = '0001_initial_tables'
branch_labels: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
